spring:
  application:
    name: pass-gen-v2

  main:
    banner-mode: off
    show-banner: false

  shell:
    interactive:
      enabled: true
    history:
      enabled: false

logging:
  level:
    root: WARN